blank_issues_enabled: true
contact_links:
  - name: bounswe2023group9 Wiki
    url: https://github.com/bounswe/bounswe2023group9/wiki
    about: You can find detailed information about our repository here.